name: 'Get Last Branch with Regex Prefix'
description: 'Gets the last semver branch with given regex prefix'
inputs:
  regex-string:  # id of input
    description: 'Regex string that is a prefix of the branch you want'
    required: true
    default: 'release-v'
outputs:
  release-branch-name:
    description: 'The latest release branch name'
  #   description: 'The full branch name that contains semantic versioning'
runs:
  using: 'node12'
  main: 'index.js'