name: 'Get Last Branch and Semantic Version Containing String'
description: 'Returns the branch name and semantic version given a string'
inputs:
  regex-string:  # id of input
    description: 'A string to filter branch names by'
    required: true
    default: "''"
outputs:
  last-semver:
    description: 'The semantic version'
  last-semver-branch:
    description: 'Branch name that contains the highest/last semantic version'
runs:
  using: 'node12'
  main: 'index.js'